### ISSUE TITLE
同步到区块高度1234298后无法继续同步

### ISSUE THREAD

**Issue by olizax** [nuls-io/nuls-v2#557]
版本：NULS_Wallet_linux64_2.4.0
系统：Ubuntu 18.04.2 LTS
区块数据为从http://nuls-cn.oss-cn-hangzhou.aliyuncs.com/2.4/data-1122020.zip下载的离线数据

Logs/block/common.log里一直报如下错误：

> 2020-02-18 04:24:14,403 ERROR [ServerProcessor-6] - io.nuls.core.rpc.netty.processor.RequestMessageProcessor.callCommands(RequestMessageProcessor.java:271):
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.invoke(RequestMessageProcessor.java:519)
        at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.callCommands(RequestMessageProcessor.java:269)
        at io.nuls.core.rpc.netty.thread.RequestOnlyProcessor.run(RequestOnlyProcessor.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null

**Comment by MIMIEYES** [comment]
@olizax 重启后问题复现吗

**Comment by lijunzhou** [comment]
@olizax 如果方便请把日志目录（logs）整体打包发到zhoulijun@nuls.io 这个邮箱。另外我们今天制作了数据包，你可以通过下载这个数据包跳过这个高度。
http://nuls-cn.oss-cn-hangzhou.aliyuncs.com/data/1380000.zip
http://nuls-usa-west.oss-us-west-1.aliyuncs.com/data/1380000.zip

**Comment by olizax** [comment]
> @olizax 重启后问题复现吗

是的



> @olizax 如果方便请把日志目录（logs）整体打包发到[zhoulijun@nuls.io](mailto:zhoulijun@nuls.io) 这个邮箱。另外我们今天制作了数据包，你可以通过下载这个数据包跳过这个高度。
> http://nuls-cn.oss-cn-hangzhou.aliyuncs.com/data/1380000.zip
> http://nuls-usa-west.oss-us-west-1.aliyuncs.com/data/1380000.zip

上次重新下载区块覆盖后解决了，现在又出现区块无法同步的问题了，报如下错误

Logs/block/block.log报

> 2020-03-23 04:21:58,391 ERROR [server-handler-request-9] - io.nuls.block.rpc.BlockResource.bestBlock(BlockResource.java:192):
java.lang.NullPointerException: null
        at io.nuls.block.rpc.BlockResource.bestBlock(BlockResource.java:189)
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.invoke(RequestMessageProcessor.java:519)
        at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.execute(RequestMessageProcessor.java:288)
        at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.callCommandsWithPeriod(RequestMessageProcessor.java:208)
        at io.nuls.core.rpc.netty.handler.message.TextMessageHandler.handler(TextMessageHandler.java:116)
        at io.nuls.core.rpc.netty.handler.message.TextMessageHandler.run(TextMessageHandler.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)


Logs/block/chain_1_block.log报

> 2020-03-23 04:19:56,275 ERROR [main] - io.nuls.block.service.impl.BlockServiceImpl.initLocalBlocks(BlockServiceImpl.java:650):
java.lang.NullPointerException: null
        at io.nuls.block.utils.ChainGenerator.generateMasterChain(ChainGenerator.java:140)
        at io.nuls.block.service.impl.BlockServiceImpl.initLocalBlocks(BlockServiceImpl.java:648)
        at io.nuls.block.service.impl.BlockServiceImpl.init(BlockServiceImpl.java:658)
        at io.nuls.block.manager.ChainManager.runChain(ChainManager.java:79)
        at io.nuls.block.BlockBootstrap.doStart(BlockBootstrap.java:126)
        at io.nuls.core.rpc.modulebootstrap.RpcModule.run(RpcModule.java:238)
        at io.nuls.core.rpc.modulebootstrap.NulsRpcModuleBootstrap.run(NulsRpcModuleBootstrap.java:81)
        at io.nuls.block.BlockBootstrap.main(BlockBootstrap.java:58)


Logs/block/common.log报

> 2020-03-23 04:23:57,624 ERROR [main] - io.nuls.block.BlockBootstrap.doStart(BlockBootstrap.java:128):block module doStart error!io.nuls.core.exception.NulsRuntimeException: Error occur when init local block
