### ISSUE TITLE
Transaction tx validator fail -type 16

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-v2#559]
This jsonrpc request to http://78.47.206.255:18004/jsonrpc:

the request: 

POST 'http://78.47.206.255:18004/jsonrpc' 
--header 'Content-Type: application/json;charset=UTF-8' 
--data-raw '{"jsonrpc":"2.0","method":"contractCall",
"params":[24442, "TTSETeCA3FWQ3Y32TCFEwJvzqGbxiXNxtkzPb3z" 
, "nuls123456",7066, 13198, 74600000, "TTSETeCA3FueL9cKCiDR8vAiRiGVtVCJksEsstM", "writeReview", "(String productId, String reviewComments) return LReviewContract$Review;", ["swimsuits","too large"], "my remark"], "id":1234}'

(sent using Postman)

almost works then stops here:

2020-02-19 16:32:05,980 ERROR [server-handler-request-4] - io.nuls.transaction.service.impl.TxServiceImpl.verify(TxServiceImpl.java:254):tx validator fail -type:16, -hash:80238237ccd4d4f7fa5769378585ffbc42c4fdb2e725d66d02e484ba688958bb 
2020-02-19 16:32:05,980 ERROR [server-handler-request-4] - io.nuls.transaction.service.impl.TxServiceImpl.newTx(TxServiceImpl.java:163):verify failed: type:16 - txhash:80238237ccd4d4f7fa5769378585ffbc42c4fdb2e725d66d02e484ba688958bb, code:sc_0102
2020-02-19 16:32:05,980 ERROR [server-handler-request-4] - io.nuls.core.log.logback.NulsLogger.error(NulsLogger.java:210):NulsException -code: [sc_0102], -msg: null
io.nuls.core.exception.NulsException: null
	at io.nuls.transaction.service.impl.TxServiceImpl.newTx(TxServiceImpl.java:165)
	at io.nuls.transaction.rpc.cmd.TransactionCmd.newTx(TransactionCmd.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.invoke(RequestMessageProcessor.java:519)
	at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.execute(RequestMessageProcessor.java:288)
	at io.nuls.core.rpc.netty.processor.RequestMessageProcessor.callCommandsWithPeriod(RequestMessageProcessor.java:208)
	at io.nuls.core.rpc.netty.handler.message.TextMessageHandler.handler(TextMessageHandler.java:116)
	at io.nuls.core.rpc.netty.handler.message.TextMessageHandler.run(TextMessageHandler.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-02-19 16:32:08,004 INFO [server-handler-request-4] - 

This is for the Portland U. project and is somewhat urgent.

**Comment by MIMIEYES** [comment]
@nmschorr 
Reason: the transfer amount is too small
Note: in the argument list, the fourth argument means that the caller is going to transfer the asset to the contract. In this case, the value of the asset is expressed in the smallest unit. You need to multiply the asset number by 10 to the power of 8

**Comment by MIMIEYES** [comment]
@nmschorr 
From the returned error message, I guess the code version you used is not the latest version. Please provide this file under the program package of the running node and send it to my email `pierreluohao@gmail.com`, I need to check.
File path: `./Modules/Nuls/transaction/1.0.0/transaction-1.0.0.jar`

**Comment by nmschorr** [comment]
Thank you Pierre - will do. But I've tried different amounts because I saw that message about it being too small.  I can do the exact same amounts using the 'cmd' tool and it works fine. I've used amounts up until my account ran out of funds. And yes I'll try the new jar.  Thank  you!

**Comment by nmschorr** [comment]
I couldn't mail it. I sent you an email with a link you can download.

**Comment by nmschorr** [comment]
[transactionjar.zip](https://github.com/nuls-io/nuls-v2/files/4228531/transactionjar.zip)
Attached the jar here.

**Comment by nmschorr** [comment]
Looks like it was jared up on Dec 2.

**Comment by MIMIEYES** [comment]
In 'CMD', the program is automatically multiplied by 10 to the power of 8 because it is aimed at the average user, which is not done for developers in 'nuls-api'

**Comment by nmschorr** [comment]
I'm aware of the biginteger problem. Although it's still very confusing to me.

This is from my python program - it shows the balance of my account first. Then I request a transaction price of 1/10th of that number and it says Insufficient balance:

balance:  {'totalBalance': '3910973458700', 'balance': '3910973458700', 'timeLock': '0', 'consensusLock': '0', 'freeze': '0', 'nonce': '9fcaf9a08c31a98f', 'nonceType': 1}
b'{"jsonrpc":"2.0","id":"99999","result":{"gasLimit":7066}}'
7066
b'{"jsonrpc":"2.0","id":"99999","result":{"gasLimit":15565}}'
15565
cgas 7066
gas_limit 15565
the request:  b'{"jsonrpc": "2.0", "method": "contractCall", "params": [24442, "TTSETeCA3FWQ3Y32TCFEwJvzqGbxiXNxtkzPb3z", "nuls123456", 7066, 15565, 391097345870, "TTSETeCA3FueL9cKCiDR8vAiRiGVtVCJksEsstM", "writeReview", "(String productId, String reviewComments) return LReviewContract$Review;", ["swimsuits", "too large"], "my remarks"], "id": "9999"}'
Traceback (most recent call last):
  File "/home/admin/workspace/psu-smart/src/call_contract.py", line 103, in <module>
    g = c.call_contract()
  File "/home/admin/workspace/psu-smart/src/call_contract.py", line 87, in call_contract
    resp1 = self.send_request(request)
  File "/home/admin/workspace/psu-smart/src/call_contract.py", line 41, in send_request
    thepair = data_d["result"]
KeyError: 'result'
b'{"jsonrpc":"2.0","id":"9999","error":{"code":"sc_0100","message":"Insufficient balance","data":null}}'

**Comment by MIMIEYES** [comment]
The order of the parameters is not correct, please refer to the order in the table below. In addition, `price` does not need to be estimated, just fill in a value greater than or equal to 25

Parameter Name | Parameter Type | Parameter Description | Required
-- | -- | -- | --
chainId | int | chain id | yes
sender | string | Transaction Creator Account Address | Yes
password | string | caller account password | yes
value | biginteger | The amount of the primary network asset that the caller transferred to the contract address. If there is no such service, fill BigInteger.ZERO | Yes
gasLimit | long | GAS Limit | Yes
price | long | GAS unit price | Yes
contractAddress | string | contract address | yes
methodName | string | contract method | yes
methodDesc | string | Contract method description, if the method in the contract is not overloaded, this parameter can be empty | No
args | object[] | List of parameters | No
remark | string | Transaction Notes | No

**Comment by MIMIEYES** [comment]
https://docs.nuls.io/Docs/i_nuls-api_JSONRPC.html#_4-2-calling-the-contract

**Comment by nmschorr** [comment]
Thank you Pierre!  Rewriting everything now.

**Comment by MIMIEYES** [comment]
You're welcome

**Comment by nmschorr** [comment]
It works! Thank you!  Fantastic!

/usr/local/bin/python3.7 /home/admin/workspace/psu-smart/src/call_contract.py
the request:  b'{"jsonrpc": "2.0", "method": "getAccountBalance", "params": [24442, 24442, 1, "TTSETeCA3FWQ3Y32TCFEwJvzqGbxiXNxtkzPb3z"], "id": "9999"}'
b'{"jsonrpc":"2.0","id":"9999","result":{"totalBalance":"3910973458700","balance":"3910973458700","timeLock":"0","consensusLock":"0","freeze":"0","nonce":"9fcaf9a08c31a98f","nonceType":1}}'
balance:  {'totalBalance': '3910973458700', 'balance': '3910973458700', 'timeLock': '0', 'consensusLock': '0', 'freeze': '0', 'nonce': '9fcaf9a08c31a98f', 'nonceType': 1}
b'{"jsonrpc":"2.0","id":"99999","result":{"gasLimit":7066}}'
gaslimit:  7066
gas_limit:  7066000
the request:  b'{"jsonrpc": "2.0", "method": "contractCall", "params": [24442, "TTSETeCA3FWQ3Y32TCFEwJvzqGbxiXNxtkzPb3z", "nuls123456", 30000000, 7066000, 27, "TTSETeCA3FueL9cKCiDR8vAiRiGVtVCJksEsstM", "writeReview", "(String productId, String reviewComments) return LReviewContract$Review;", ["swimsuits", "too large"], "my remarks"], "id": "9999"}'
b'{"jsonrpc":"2.0","id":"9999","result":{"txHash":"67073d25f1688fc1534714967d938ceb19d7e7a06581999565e788681964cdb2"}}'
{'txHash': '67073d25f1688fc1534714967d938ceb19d7e7a06581999565e788681964cdb2'}
None

**Comment by MIMIEYES** [comment]
Although this is fine, the value 'gasLimit' does not need to be multiplied by 1000
